### ISSUE TITLE
Comments in Notion seem to add whitespace at beginning and end

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/notion-markdown-cms#4]
This currently breaks our CtaButton for cloudfoundation.meshcloud.io

See the following code block in Notion:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/14248574/158349563-1a4876a4-1f7f-40a6-a596-ad958a97bcbc.png">

The raw code ends up to be:

```
<!--notion-markdown-cms:raw-->
<CallToAction>
  <CtaHeader>Self-Service Tenant Provisioning</CtaHeader>
  <CtaText>See a fully automated tenant provisioning process live in action or learn more on best practices for tenant management.</CtaText>
  <CtaButton class="btn-primary" url=" https://www.meshcloud.io/use-case-cloud-zones/ ">Get a Demo</CtaButton>
  <CtaButton class="btn-secondary" url="https://www.meshcloud.io/2021/01/27/cloud-tenant-management-what-you-need-to-know-in-2021/">Learn More</CtaButton>
</CallToAction>
```

**Comment by JohannesRudolph** [comment]
Cool, I've encountered this bug before but couldn't make sense of it. I "fixed" it at the time by just copy/pasting the code in the code block, which seems to have changed how notion laid it out in rich text blocks (one big block vs. split in multiple RT blocks)
